services:
  db:
    image: postgres:13
    container_name: movieflix_db_container
    environment:
      POSTGRES_DB: movieflix_db
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: